const fs = require("fs");
const path = require("path");
const PptxGenJS = require("pptxgenjs");
const { titleSlide } = require("../templates/slide-templates");
const { themeColors } = require("../templates/shared-constants");

const outputDir = process.argv[2] || "output/decks";
const fileName = process.argv[3] || "test.pptx";

fs.mkdirSync(outputDir, { recursive: true });

const deck = new PptxGenJS();
const slide = deck.addSlide();

titleSlide(slide, {
  heading: "Persado PMM Execution Layer",
  subheading: "Test deck generated by scripts/build-deck.js",
  backgroundColor: themeColors.primary,
});

deck.writeFile({ fileName: path.join(outputDir, fileName) }).then(() => {
  console.log(`Deck written to ${path.join(outputDir, fileName)}`);
});
